mattermost/mattermost-plugin-api

logrus.go, logrus_test.go
`LogrusHook` is a `logrus.Hook` for emitting plugin logs through the RPC API for inclusion in the server logs. To configure the default `Logrus` logger for use with plugin logging, simply invoke:
```go
pluginapi.ConfigureLogrus(logrus.StandardLogger)
```
Alternatively, construct your own logger to pass to pluginapi.ConfigureLogrus. A more complete example:
```go
func (p *Plugin) OnActivate() error {
pluginapi.ConfigureLogrus(logrus.StandardLogger(), p.API)
logrus.SetLevel(logrus.TraceLevel)
return nil
}
// ServeHTTP demonstrates a plugin that handles HTTP requests by greeting the world.
func (p *Plugin) ServeHTTP(c *plugin.Context, w http.ResponseWriter, r *http.Request) {
logrus.Error("ERROR")
logrus.Warn("WARN")
logrus.Info("INFO")
logrus.Debug("DEBUG")
logrus.Trace("TRACE") …
```
=> introduce logrus proxying

README.md, client.go, error.go, example_client_test.go, user.go, user_test.go
This commit only solves the problem that is `*model.AppError`, but otherwise proxies through the underlying API unchanged at this time.
=> bootstrap client and user service

kv.go, kv_test.go
MM-23163 - KV.Get() for a non-existant key should not return an error
Fixes https://mattermost.atlassian.net/browse/MM-23163
=> MM-23163 - KV.Get() for a non-existent key should not return an error

cluster/job.go, cluster/job_example_test.go, cluster/job_test.go, cluster/mock_plugin_api_test.go, cluster/mutex.go, cluster/mutex_example_test.go, cluster/mutex_test.go, cluster/wait.go
This branches off https://github.com/mattermost/mattermost-plugin-api/pull/33 to add support for locking with a context (and thus implicitly supporting lock cancellation, "try lock" semantics, etc.).
I opted not to merge directly to `master` given the rework happening in that active PR.
=> cluster: support LockWithContext

cluster/job.go, cluster/job_example_test.go, cluster/job_test.go
Parameterize the function for computing a job's next wait interval, and provide two implementations by default:
* `MakeWaitForInterval`: the existing semantics of spacing runs by a configured interval
* `MakeWaitForRoundedInterval`: a variation of the above that rounds (really, truncates) to that interval, so as to consistently run, say, every 5 minutes on 0:00, 0:05, 0:10, ... even if the job is paused for some reason. In other words, it won't drift out of sync relative to the clock. It doesn't guarantee /never/ running less than the interval, since if it's been longer than the required interval it just runs right away.
@mickmister, hopefully this addresses your needs with the MS calendar plugin: but if not, hopefully you can provide your own wait interval function. Let me know if you …
=> Support externally defined wait intervals

channel.go, channel_test.go
Calling `pluginAPI.AddUserToChannel(...)` can lead to a race condition if it is proceeded by `CreateChannel` as `AddUserToChannel` first calls [`api.GetChannel`](https://github.com/mattermost/mattermost-server/blob/aa47b4633f18eed917c70263d139376f15d8778c/app/plugin_api.go#L422) to validate channel before adding the user. `GetChannel` uses a replica if one exists and if data hasn't reached consistency, this call returns a `channel not found error`. Solution is to wait for channel creation to propagate through replicas before returning success from `Channel.Create(..)`
Fixes https://mattermost.atlassian.net/browse/MM-24456
=> MM-24456 - CreateChannel followed by AddChannelMember is racy when a replica exists

store.go
Corey had mentioned during the Incident Response architecture review meeting that maximum `2` open connections for each plugin seems low. This is to bump that to a reasonable number compared to the default value we use in the server, which is [`300`](https://github.com/mattermost/mattermost-server/blob/e6bbb4bd7abf50c9bb685d1326c3fc7556aa93fb/model/config.go#L1009). Bumping to a 5% of the default value i.e. `15` connections. Making this change since it's a quick change so we don't have to worry about it later.
Also used https://www.alexedwards.net/blog/configuring-sqldb as a reference, which suggests `25` per a medium sized application.
Fixes https://mattermost.atlassian.net/browse/MM-25702
=> MM-25702 - Increase MaxOpenConns when creating DB handles in mattermost-plugin-api

bot_test.go, botensure.go
This effectively cherry-picks https://github.com/mattermost/mattermost-server/pull/14103 into the plugin api wrapper, in anticipation of removing the helpers altogether in a future v6.0. Bringing over the missing unit tests as well.
Fixes: https://mattermost.atlassian.net/browse/MM-23502
=> MM-23502: update EnsureBot

configuration.go, configuration_test.go
Add calls to `Config.SetDefaults()` before returning configuration in `ConfigurationService`, to prevent config from containing `nil` values.
Fixes https://github.com/mattermost/mattermost-server/issues/14939
=> [GH-14939] Set defaults on API Config

go.mod, go.sum, i18n/doc.go, i18n/i18n.go, i18n/i18n_test.go
This package provides the needed tools to allow plugins to quickly add support for i18n.
I chose too alias most of they `types` from github.com/nicksnyder/go-i18n/v2 to prevent consumers of this library to import them there self. `Bundle` is composed of `go-i18n.Bundle`, which allows for flexible use. To simplify the API, `Bundle.Bundle` could be made private.
Fixes https://github.com/mattermost/mattermost-plugin-api/issues/14
=> Add i18n package

experimental/flow/steps/empty_step.go, experimental/flow/steps/freetext_step.go, experimental/flow/steps/simple_step.go, experimental/freetextfetcher/freetext_fetcher.go, experimental/freetextfetcher/freetext_fetcher_manager.go, experimental/freetextfetcher/handler.go, experimental/freetextfetcher/store.go, experimental/panel/settings/bool_setting.go, experimental/panel/settings/empty_setting.go, experimental/panel/settings/freetext_setting.go, experimental/panel/settings/option_setting.go, experimental/panel/settings/read_only_setting.go, experimental/panel/settings/setting.go, experimental/panel/settings/store.go
Add fallback to slack attachments messages from panel and flow.
None
=> Add fallback to slack attachments and add missing comments

license.go, license_test.go, store.go, store_test.go
Port the changes from incident response to skip the license check when `EnableDeveloper` and `EnableTesting` is true. These bits are not suitable for use in production, and allow for development testing under the source available license without having to run the enterprise server binary.
Once merged, I'll leverage same in incident response both to simplify the code there and allow our use of the SQL store under the same circumstances.
Fixes: https://mattermost.atlassian.net/browse/MM-28104
=> allow development mode when checking license

experimental/command/command.go
Add a helper method to get the icon data for slash command autocomplete.
Related to https://github.com/mattermost/mattermost-plugin-github/pull/359
=> Add GetIconData

experimental/bot/logger/default_logger.go, experimental/common/logapi.go
This allows plugins to just pass `p.API` to `logger.New`
None
=> Use same naming pattern for LogAPI as for plugin API

error.go
Simplify handling of errors by converging on a common `StatusNotFound` error instead of having to discover if the returned `error` is an `*model.AppError` and examine the `StatusCode`.
Example usage:
```go
user, err := r.pluginAPI.User.GetByUsername(username)
if errors.Is(err, pluginapi.ErrNotFound) {
pluginAPI.Log.Info(fmt.Sprintf("Unable to find user @%s", username)))
return
} else if err != nil {
pluginAPI.Log.Warn(fmt.Sprintf("Unable to find user @%s", username)), "err", err)
return
}
```
=> return ErrNotFound when normalizing errors

store.go
Setting a high number of MaxOpenConns reduce our capabilities to scale in cloud where multiple customers are packed in a single multi-tenant database host. The problem was observed when we noticed an abnormally high amount of connections on our writer nodes in cloud.
Writer nodes had >600 connections open whereas reader nodes had ~200. This was very confusing because our workload is primarily read-heavy, and we have observed the ratio of writer:reader connections to be 1:10. So having more writer conns than readers meant that something was going very wrong somewhere.
@angeloskyratzakos was kind enough to debug this with me and he ran a top idle query on a master node in prod, and we saw than 99% of the idle queries were the incident response plugin running SELECT queries. So looking at …
=> MM-31230: Limit the number of idle connections from a plugin

cluster/job.go, cluster/job_test.go
I want to export `jobMetadata` because creating custom `NextWaitInterval` is impossible right now. This is a problem because one must use a custom `NextWaitInterval` to create more advanced scheduling mechanisms using `Schedule`.
N/A
=> Export jobMetadata to allow creation of custom NextWaitInterval

store.go, store_test.go
When we designed the store access in the pluginapi, we made the conscious decision to enforce an E20 license (outside of developer environments).
Unfortunately, this limitation has caused us trouble in Incident Collaboration, where we want to be able to start up the plugin even without a valid E20 license, and selectively enable certain functionality for non-E20 licensed customers. Since the pluginapi enforces E20, we can't get our base functionality off the ground.
After further review, we have decided to simply [lift this restriction altogether](https://community-daily.mattermost.com/core/pl/3akxk61ebjfqmbbh588pn5mrjr). It was always possible to work around anyway.
None.
=> Relax store license restrictions

license.go, license_test.go
Add a function to check whether the server is E10-licensed, using the LDAP feature as the flag.
--
=> Add E10 license check

experimental/bot/mocks/mock_logger.go, go.mod, go.sum, license.go, license_test.go, system.go, system_test.go
Adds a RequestTrialLicense that gracefully degrades in servers with a version lower to 5.36.0
This needs to wait for https://github.com/mattermost/mattermost-server/pull/17551 to be merged.
Needed by https://mattermost.atlassian.net/browse/MM-34665
=> Add version-aware RequestTrialLicense to System

license.go
This PR updates the  license checks to use the proposed new way of detecting them. The details are [in this document](https://docs.google.com/document/d/1PhlIiGXbAl-sTRFXLRT5R71eSzUTA0HXAVNXPu1aAVU/edit), but the gist of it is that we are now using the SKU shortname instead of specific features. As the old names will be in use for at least two more years, we need to check for both the old ones (E10, E20) and the new ones (professional, enterprise). The possible names are the keys in this map: https://github.com/mattermost/customer-web-server/blob/master/licenses/licenses.go#L98
As a fallback for legacy licenses with potentially unknown SKU shortnames, we default to the old way of looking at a specific feature that we know is in the license we are checking. …
=> MM-36167: Use SKU short name with feature check as fallback

.circleci/config.yml, .golangci.yml, go.sum
This PR fixes a couple of issues with the pipeline
- Update golangci-lint version to fix the tool from getting killed
- Update go version to stay up to date
- Update codecov orb version to fix report
- `go mod tidy`
- Remove/replace deprecated linters
-  Disable  `fieldalignment` 
None
=> Update pipeline dependencies

channel.go, channel_test.go, go.mod, go.sum
Add CreateSidebarCategory, GetSidebarCategories and UpdateSidebarCategories to PluginAPI Channel Service
JIRA: https://mattermost.atlassian.net/browse/MM-32421
```release-note
Added CreateSidebarCategory, GetSidebarCategories and UpdateSidebarCategories to PluginAPI Channel Service
```
=> MM-32421: Extend channel sidebar category APIs for PluginAPI

bot_test.go, channel_test.go, client.go, configuration_test.go, emoji_test.go, example_client_test.go, experimental/bot/poster/default_poster_test.go, file_test.go, go.mod, go.sum, kv_test.go, logrus_test.go, plugin_test.go, post_test.go, store.go, store_test.go, system_test.go, team_test.go, user_test.go
- Reverts #93 so that IC plugin can revert its DB RPC API change, see thread: https://community-daily.mattermost.com/private-core/pl/7ag51xd7q7dxpy1hqqjax38ofo
=> Revert "Add DB RPC API support to client (#93)"

bot_test.go, channel_test.go, client.go, configuration_test.go, emoji_test.go, example_client_test.go, experimental/bot/poster/default_poster_test.go, file_test.go, go.mod, go.sum, kv_test.go, logrus_test.go, plugin_test.go, post_test.go, store.go, store_test.go, system_test.go, team_test.go, user_test.go
- Reverts the revert in #98 . Turns out, the DB RPC-related commits were not the problem. Apologies for the trouble.
=> Revert "Revert "Add DB RPC API support to client (#93)" (#98)"

bot_test.go, emoji_test.go, experimental/command/command.go, file.go, file_test.go, go.mod, i18n/i18n.go, i18n/i18n_test.go, logrus.go, system_test.go, team.go, team_test.go, user.go
`io/ioutil` is deprecated, so let's use the appropriate packages instead
None
=> Migrate away from using io/ioutil

experimental/flow/flow.go, experimental/flow/handler.go, experimental/flow/state.go, experimental/flow/step.go
Targets: https://github.com/mattermost/mattermost-plugin-api/pull/111
- Added `GetCurrentStep` to API
- Removed `Do` and `Done` from API
- Fixed NPE if`handleDialog` returned an error map but no error
- `State` is now an `Map[string]interface{}` with some getterns
- Added `OnRender` option to step
- Added `WithColor` option to step
- If `forwardTo` is set, the next step will be automatically processed.  Use `""` to go to the next step.
None
=> Flow improvements 

.gitignore, bot.go
Add a `TODO` comment to `bot.go` about moving `EnsureBot` method to mattermost-server repository.
=> bot: Add a comment to bot.go about EnsureBot method

cluster/job_once.go, error.go, errors/error.go, logrus.go, logrus_test.go
This change accompanies a Playbooks PR to improve the logging story with `logrus`:
* Set `logrus.TraceLevel` by default so that the server gets all logs and can do its own filtering. Plugins that forget to set a level end up with `logrus.InfoLevel` and have no way to programmatically enable debug logs.
* Add a `plugin_caller` field to logging events, tracing the logger from the plugin's perspective instead of having the server clobber it with a `caller` that's just `app/plugin_api.go`.
As part of this, I also eliminated the `errors` package, avoiding the circular dependency with `cluster` by just simplifying the version of `normalizeAppError` there.
None.
=> Improved logrus logging

experimental/command/info.go
Since go1.18 [`debug.BuildSetting`](https://pkg.go.dev/runtime/debug@go1.18beta2#BuildSetting) is provided as part of [`debug.BuildInfo`](https://pkg.go.dev/runtime/debug@go1.18beta2#BuildInfo). It contains build information like the build commit or build time. 
This PR adds a helper helper which allows them to easily create a `about` command for easier debugging, without any build flags.
An example usage on the plugin side can be found [here](https://github.com/mattermost/mattermost-plugin-github/commit/0e7ae53899bfc84ae342288e87e59dff6b36cab9).
None
=> Add build info command helper

store.go
If ` pluginapi.NewClient` is called with no driver i.e. `pluginapi.NewClient(p.API, nil)` any call to the DB store will panic. This PR changes the code to be more defensive and return an error for that case.
None
=> Don't panic if no driver is provided

experimental/telemetry/doc.go, experimental/telemetry/tracker.go
Add the ability to enable/disable telemetry trackers at pluginAPI.
The main goal is to get tracker/client creation together and avoid hook order race conditions that end up with trackers with null clients or flowmanagers with outdated trackers.
Related gihub plugin pr https://github.com/mattermost/mattermost-plugin-github/pull/659
Add `Enable` and `Disable` to the Tracker interface and implementations to the tracker struct.
All telemetry client & tracker initialization is done at onActivate, and OnConfigurationChange will only take care of config reload.
OnActivate
```go
// Telemetry client
p.telemetryClient, err = telemetry.NewRudderClient()
if err != nil {
p.API.LogWarn("Telemetry client not started", "error", err.Error())
return
}
// Get config values
p.tracker = telemetry.NewTracker( …
```
=> Mm 51400 enable disable tracking

experimental/telemetry/doc.go
As far as I can tell, no plugin makes use of this env variable currently, so there is no need to rename it somewhere else.
https://community.mattermost.com/private-core/pl/9wxkzzicj3ns5j3q99xtrpuduy
=> Fix rudder data plane env variable
