mattermost/mattermost-plugin-api

- dlock/README.md
- dlock/dlock.go
- dlock/dlock_test.go
- dlock/dlocktest/dlocktest.go
- go.sum
Hey, here is the initial version of dlock. Thanks!
closes https://github.com/lieut-data/mattermost-plugin-api/issues/20
> added dlock (distributed lock) -alpha

- README.md
- go.mod
- go.sum
- kv.go
- kv_test.go
- No more custom fork
- KVSet is synced up with the fix on MM `master`
cc @ilgooz
> Fix kv set and move back to upstream

- botensure.go
Added missing `EnsureBotOption` functions to be able to add bot image options to `EnsureBot`.  
https://github.com/mattermost/mattermost-plugin-api/pull/39 Migrated `EnsureBot` functionality
> Added ensureBotOption functions

- client.go
- go.mod
- go.sum
- store.go
- store_test.go
* `StoreService` exposes:
* `GetMasterDB`
* `GetReplicaDB`
* `Close`
* `StoreService` returns an error if a valid license is not found
* Added tests for `StoreService`
Fixes https://mattermost.atlassian.net/browse/MM-24996
> MM-24996 - Expose database API through mattermost-plugin-api

- .golangci.yml
- bot_test.go
Follow up on https://github.com/mattermost/mattermost-plugin-api/pull/52
> Fix more linter errors

- post.go
Add the DM helper function to the PostService.
None
> Add DM to post api

- .circleci/config.yml
> Bump codecov orb

- experimental/telemetry/tracker.go
Check for nil properties on telemetry
None
> Check for nil properties

- experimental/bot/logger/default_logger.go
- experimental/bot/logger/logger.go
- experimental/bot/logger/nil_logger.go
- experimental/bot/logger/test_logger.go
That allows for easier logging of error in an idiomatic way.
None
> Add WithError method to Logger

- experimental/telemetry/doc.go
Add usage documentation for telemetry
None
> Add usage documentation for telemetry

- experimental/oauther/oauth2.go
- experimental/oauther/oauth2_complete.go
Fixed JSON unmarshaling in experimental/oAuther
none
> Fixed JSON unmarshaling in experimental/oAuther

- README.md
Navigating to the given link produces a 404. This PR keeps the text shown to the user the same but fixes the destination link.
n/a
> fix broken README link

- license.go
Export `IsConfiguredForDevelopment` to allow plugins to use it.
Needed for https://mattermost.atlassian.net/browse/MM-33404
> Export IsConfiguredForDevelopment

- license_test.go
This PR addresses [this comment in the previous PR](https://github.com/mattermost/mattermost-plugin-api/pull/91#pullrequestreview-683988518).
The original PR was merged faster than I was able to push these tests, but as I had already implemented them, why not open this new one to add them.
Only asking for one dev review because this adds just tests.
https://mattermost.atlassian.net/browse/MM-36167
> MM-36167: Test SKU shortname cases in license checks

- channel.go
Fix method versions
Fixes https://mattermost.atlassian.net/browse/MM-37314
> [MM-37314] Fix categorization method version

- experimental/common/slack_attachments.go
- experimental/flow/handler.go
- experimental/freetextfetcher/handler.go
- experimental/panel/handler.go
- go.mod
- go.sum
Fix the breaking changes from https://github.com/mattermost/mattermost-server/pull/18070
None
> Update to latest commit of github.com/mattermost/mattermost-server/v6

- go.mod
- go.sum
- session.go
Changes for https://github.com/mattermost/mattermost-server/pull/18958
https://mattermost.atlassian.net/browse/MM-39851
> [MM-39851] Add CRUD methods for user sessions to plugin API

- experimental/flow/flow_controller.go
- experimental/flow/handler.go
- experimental/freetextfetcher/freetext_fetcher.go
- experimental/freetextfetcher/store.go
- The validation method of a `freetextFetcher` can now be `nil`
- Fix freetext message processing
- Remove global `Init` method for flow handler
None
> Various flow improvements 

- experimental/flow/flow.go
- experimental/flow/state.go
See https://github.com/mattermost/mattermost-plugin-api/issues/113
Fixes https://github.com/mattermost/mattermost-plugin-api/issues/113
> GetCurrentStep() should not return an error if now flow is running.

- experimental/flow/step.go
`Step.WithImage`:
- No longer require pluginURL as parameter
- Accept full HTTP(s) URLs
none
> Flow: Step.WithImage improvement

- experimental/command/info.go
Follow up on https://github.com/mattermost/mattermost-plugin-api/pull/121
> Add notice to build info if build is dirty
